# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.7.0'
gem 'curses', '~> 1.2.4'
gem 'rainbow', '~> 2.2.2' # https://github.com/sickill/rainbow
